{% set name = "topoflow" %}
{% set version = "3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/mdpiper/topoflow

requirements:
  build:
    - python
    - numpy
    - scipy
    - h5py
    - netcdf4
  run:
    - python
    - numpy
    - scipy
    - h5py
    - netcdf4

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

test:
  imports:
    - topoflow
    - topoflow.components

about:
  home: http://csdms.colorado.edu/wiki/Model:TopoFlow
  license: MIT
  license_file: LICENSE.txt
  summary: Spatial hydrologic model (D8-based, fully BMI-compliant)
  dev_url: https://github.com/peckhams/topoflow
